### ISSUE TITLE
doesn't work on Windows 7

### ISSUE THREAD

**Issue by injectify-js** [Mr-Un1k0d3r/ThunderShell#16]
Hi. How can I run payload ps on Windows 7 powershell v2? Do you have any ideas? It doesn't work on Windows 7.

**Comment by Mr-Un1k0d3r** [comment]
I will add a video in the wiki to show how to use get a session shortly hope it will help in the future

**Comment by injectify-js** [comment]
I mean, on Windows 7, the payload ps code doesn't work at all. On Windows 10 there are no such problems. Which version powershell and version Net framework works your payload? Thanks.

**Comment by Mr-Un1k0d3r** [comment]
The default version that I was using during my test was the following one
```
PS C:\>$psversiontable

Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.2.9200.22198
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2
```

**Comment by Mr-Un1k0d3r** [comment]
Does it return any useful errors or you simply don't get your connect back without errors?

**Comment by injectify-js** [comment]
There are no errors on the server. There are not enough libraries in the console when the payload starts. On .Net 2.0 will not work.

**Comment by injectify-js** [comment]
Hello. Many thanks for your work and for the time you give! I would be very grateful if you could solve the problem with .net version 2.0 of the payload! How long do you think it will take you?

**Comment by Mr-Un1k0d3r** [comment]
I will take a look at it but functionalities in .net 2.0 are limited especially from a HTTP request perspective.
