### ISSUE TITLE
the interaction commands with the victim  not working 

### ISSUE THREAD

**Issue by aoprea1982** [Mr-Un1k0d3r/ThunderShell#2]
Like the title says cannot send remote commands. 

The error:
![thundershell17](https://user-images.githubusercontent.com/16059481/31064128-88f02872-a774-11e7-8039-cc2334824732.jpg)

1. Operating system used to compile and run ThunderShell 
Kali Linux 2017.2

2. Victim machine 
Windows 10 pro x64 version 1703 

3. Shell command / script / task you were trying to run.
Running whoami command . 
![thundershell17](https://user-images.githubusercontent.com/16059481/31064128-88f02872-a774-11e7-8039-cc2334824732.jpg)

**Comment by Mr-Un1k0d3r** [comment]
After a bit of research this issue seems to be caused by the fact the IE profile is not initialized yet. As the error suggest adding the -UseBasicParsing should fix the issue. I'm going to update the code to support cases where profile was never initialized.
