### ISSUE TITLE
Warning in Version 2.1.2 (11/01/2019) 

### ISSUE THREAD

**Issue by injectify-js** [Mr-Un1k0d3r/ThunderShell#23]
Hello
When starting server I got this:
 * Serving Flask app "core.gui" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Version 2.1.2 (11/01/2019)
This WARNING is a problem or it's just warning for attention and ThunderShell works good?

**Comment by tazz0** [comment]
just for clarification are you running this on kali ?

If the answer is yes it's because kali seems to have a different version of the flask package installed and the behavior differ from what I have been working on (Ubuntu 18.04.1) I will see if I can suppress this message in the next release.

**Comment by injectify-js** [comment]
I'm working on Ubuntu 16.04.5. 
Thank you, I'll wait for the next release.

**Comment by Mr-Un1k0d3r** [comment]
We tried to reproduce the issue locally without success. To be able to troubleshoot it more efficiently can you provide more details about the version of python / flask you are using. 

Thank you
