### ISSUE TITLE
Shell Command On GUI Not Working

### ISSUE THREAD

**Issue by th1k404** [Mr-Un1k0d3r/ThunderShell#25]
Hello, first of all thanks for your project it really helpful for me to do a research on rat.

I have installed this project on kali linux 2018.4 as my attacker server and windows 10 as my target.

my issue is when i interacted the shell from ps or exe file successfully on the windows 10 machine, i cannot access any command from the shell GUI (the button send is not working).

From the terminal i can use the command normally (ex: ipconfig)

![2019-02-08_144828](https://user-images.githubusercontent.com/40754359/52465380-02576b00-2bb1-11e9-8fb6-abbedd1a5c6e.png)
Note: the screenshot above is only show the command that i type from terminal.

is there a bug or my system fault?

Thanks,

**Comment by Mr-Un1k0d3r** [comment]
This is a known bug that's currently addressing. This should be fixed shortly. Keep in mind that the project is under active development since we added the web interface. I will try to do my best to commit the change during the weekend.

**Comment by th1k404** [comment]
Okay sir noted with thanks.

**Comment by Mr-Un1k0d3r** [comment]
this issue was fixed.
