### ISSUE TITLE
Not working HTTPS Version 3.0.0 (04/02/2019)

### ISSUE THREAD

**Issue by injectify-js** [Mr-Un1k0d3r/ThunderShell#26]
Hello
Not working HTTPS. When I connected the GUI via HTTPS, I got it:

Ubuntu 18.04.2 LTS /64
Python 3.6.7
Flask 1.0.2
Gevent 1.4.0
-------------------------------------------------------------------------------------------------------------------------------------------

[*] Current Active CLI session UUID is 4c10f010-8a64-4268-8546-2asf96r6dc9d
[*] Web GUI Started: https://192.168.1.100:45654
[*] Web GUI Password: reFyhTHOLyJgfqKkRrebyhTk
[*] Starting web server on port 4034

(Main)>>> [+] Web server is using HTTPS
<gevent._socket3.socket object, fd=8, family=2, type=2049, proto=0>: Invalid http version: '\x16\x03\x01\x02\x00\x01\x00\x01\x03\x03\x95,$CE[m.NJx16\x14\x82pV_\x9c\
x86Ax81\x90^nx94m F\r{\x8b;|\x9f\x10K\x12_8\x97\x05"\x19\x00"\x13\x03\x13\x01\x13\x0_+/,0\x13\x14\x00\x9c\x00\x9d\x00/\x005\x00\n'
<gevent._socket3.socket object, fd=9, family=2, type=2049, proto=0>: Invalid HTTP method: '\x16\x03\x01\x02\x00\x01\x00\x01\x03\x03*\x88\x8c\x01k\x7f\x0bkx00A!\x99\
x17\x87x13\x03h\x07 x10\x92\x0b}{w[!S"%\x84\tpN4}~X\x00"\x13\x03\x13\x01\x13\x0_+/,0\x13\x14\x00\x9c\x00\x9d\x00/\x005\x00\n'
<gevent._socket3.socket object, fd=8, family=2, type=2049, proto=0>: Invalid HTTP method: "\x16\x03\x01\x00x01\x00\x00\x03\x03\x1fZ\x93\x8b\x88P\x14|\x0f<|#u'\x01_b
\x00\x00\x1_+/,0\x13\x14\x00\x9c\x00\x9d\x00/\x005\x00\n"

**Comment by Mr-Un1k0d3r** [comment]
I totally forgot to validate the HTTPS version after it was migrated to python3. Working on it.

**Comment by Mr-Un1k0d3r** [comment]
I addressed the issue the config file was also updated to include a different certificate if you want to use different interfaces for the listener and the web UI.
