### ISSUE TITLE
RC4 Cipher

### ISSUE THREAD

**Issue by gbiagomba** [Mr-Un1k0d3r/ThunderShell#3]
Hello,

By using RC4, the tool is susceptible to a Sweet32 birthday attack. I would avoid RC4, DES, and CBC ciphers. I would recommend using something stronger. 

https://sweet32.info

**Comment by Mr-Un1k0d3r** [comment]
There is plenty of attacks that you can use against RC4. The easiest one is probably known plaintext attack in this case. The idea behind RC4 is quite simple I wanted an algorithm that is quite small to implement without requiring 3rd parties library. The encryption is used to hide the traffic to avoid detection by security products not to provide integrity.
