### ISSUE TITLE
Installation Error (crypto.cipher, python3.7-pip)

### ISSUE THREAD

**Issue by Comanio00** [Mr-Un1k0d3r/ThunderShell#33]
Hey.
I'm trying to install the program on Ubuntu 18.04 64, python3.7.3, pip3, pycrypto. Errors appear during installation:
`cannot import name '_ARC4' from 'Crypto.Cipher' (/usr/lib/python3/dist-packages/Crypto/Cipher/__init__.py)`
`E: Unable to locate package python3.7-pip`
`E: Couldn't find any package by glob 'python3.7-pip'`
`E: Couldn't find any package by regex 'python3.7-pip'`

Tell me how you can solve the problem?

**Comment by Mr-Un1k0d3r** [comment]
The installer is trying to install both python3 or python3.7. The reason behind this is that some distro have python3 < 3.7. I'm trying to standardize the code to support python3 and I decided to support python >= 3.7.

I think that ubuntu python3 is 3.7 and the installer should have been able to install it properly.

Here is the code behind it.

```
Utils.install_dependencies("3")
Utils.install_dependencies("3.7")
```

Were you able to run the tool after the installation? are you still have some packages missing?

**Comment by Comanio00** [comment]
Installed dependencies for python3.7.
Only one problem remained:

E: Unable to locate package python3.7-pip
E: Couldn't find any package by glob 'python3.7-pip'
E: Couldn't find any package by regex 'python3.7-pip'
sh: 1: pip3.7: not found
sh: 1: pip3.7: not found
sh: 1: pip3.7: not found
sh: 1: pip3.7: not found
sh: 1: pip3.7: not found
sh: 1: pip3.7: not found

The problem is that 'python3.7-pip' does not exist in the ubuntu 18.04 repository, but there is a 'python3-pip'. What do you need to fix in the code so that it installs only 'python3-pip'?

**Comment by Mr-Un1k0d3r** [comment]
I've updated the setup by default it will only install python3 dependencies if you need more specific version of python3 if the repo are outdated the UI will show the switch options instead

**Comment by Comanio00** [comment]
Changes helped. Pip3 error has passed. Now the file install.lock is not created, all necessary packages are installed. After restarting the program, installation begins again.

**Comment by Mr-Un1k0d3r** [comment]
You most likely have changed the permission of the folder the creation of the install.lock file is not part of the setup.

I installed a fresh version from github and tried with an already installed and both worked as expected

**Comment by Comanio00** [comment]
Thank you. The problem was in python3.7. Moved to python3.6 and the problem disappeared. The program works.
