### ISSUE TITLE
Feature Request: Download

### ISSUE THREAD

**Issue by brsmathers** [Mr-Un1k0d3r/ThunderShell#35]
Hello! Any plans to implement a download capability in order to pull down files from a target? Very nice RAT, btw.

**Comment by Mr-Un1k0d3r** [comment]
I genuinely thought I implemented the feature but I only implemented the read I can add the download feature without problem (Just need to find some free time to do it)

**Comment by brsmathers** [comment]
Lol I can understand that. Thanks for the quick response! Looking forward to the add.
