### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Jimani333** [Mr-Un1k0d3r/ThunderShell#43]
Hello.When the .exe is opened in victims pc its running for a little and crashes.What's the porblem ?

**Comment by Mr-Un1k0d3r** [comment]
I'm going to need a bit more details. what command did you run did you get any errors?

**Comment by Jimani333** [comment]
I open in laptop the .exe file which ThunderShell produce.It opens and connect to the server very well.
It can also take screenshot.After one minute about , it crashes and says that the .exe file stop working

Thanks in advance

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Mr-Un1k0d3r** [comment]
I may have identified a case that is causing a crash working on a fix. Not sure if it's the same issue that you faced but it may fix it.

**Comment by Mr-Un1k0d3r** [comment]
I pushed an update to address the issue I found long story short when the network is timing out for whatever reason I was catching the exception with a `try` `finally` I now added the `catch` part to catch the exception this may fix your issue

**Comment by fgabcy** [comment]
it takes forever to open the Web GUI Started: http://192.168.*.*:13337
at the end it won't display anything.

**Comment by Mr-Un1k0d3r** [comment]
did you got a stack trace or any kind of error. Also does the config is using the right IP address?

**Comment by fgabcy** [comment]
> did you got a stack trace or any kind of error. Also does the config is using the right IP address?

except intall.lock which I got on my first launch and there was no error after that. Or it doesn't work on NAT?

**Comment by Mr-Un1k0d3r** [comment]
should work on NAT assuming you are using a VM on a local system. Can you share your current config file.

**Comment by fgabcy** [comment]
![Uploading test1.jpg…]()
