### ISSUE TITLE
New feature request - autocomand (with proposal on how to do)

### ISSUE THREAD

**Issue by tristandostaler** [Mr-Un1k0d3r/ThunderShell#9]
Add in default.json:
 "autocommand": "whoami",

Add in core/parser.py:
in __init__:
    self.autocommand = self.config.get("autocommand")

in register, last line of the function:
    self.output =  self.autocommand

**Comment by Mr-Un1k0d3r** [comment]
I'm assuming you want auto command when the shell is connecting back? I will add the feature

**Comment by Mr-Un1k0d3r** [comment]
Feature added

**Comment by tristandostaler** [comment]
Thanks!
